language: php

php:
      - 5.3
          - 5.4
              - 5.5

before_install:
      - wget http://cs.sensiolabs.org/get/php-cs-fixer.phar

before_script:
      - composer self-update
          - composer install --dev
